using System;
using System.Collections.Generic;
using System.Text;

namespace PM.Data
{
    /// <summary>
    /// 数据库字段
    /// </summary>
    public class DbFields
    {
        public const string ORGANIZATION = "[ORGANIZATIONID],[ORGID],[DESCRIPTION],[ORGTYPE],[LEVEL_],[COMMENTS],[LEADER],[PHONE],[ADDRESS],[PARENT]";

        public const string LOCATIONS = "[LOCATIONSID],[LOCATION],[DESCRIPTION],[TYPE],[DISABLED],[EXTERNALREFID],[ISREPAIRFACILITY],[X],[Y],[Z],[ORGID],[OWNERSYSID],[SENDERSYSID],[SERVICEADDRESSCODE],[SITEID],[SOURCESYSID],[STATUS],[STATUSDATE],[CHANGEBY],[CHANGEDATE]";

        public const string LOCHIERARCHY = "[LOCHIERARCHYID],[LOCATION],[PARENT],[CHILDREN],[ORGID],[SITEID],[SYSTEMID]";

        public const string MEASUREPOINT = "[MEASUREPOINTID],[POINTNUM],[DESCRIPTION],[DISPLAYSEQUENCE],[IPADDRESS],[CARDNUM],[DEVICENUM],[SERVERIP],[SERVERPORT],[METERNAME],[ORGID],[SITEID],[LOCATION],[CARRIER],[SUPERVISOR],[PHONE]";

        public const string MEASUREPOINTPARAM = "[MEASUREPOINTPARAMUID],[POINTNUM],[MEASUREUNITID],[LOWERWARNING],[LOWERACTION],[LLPMNUM],[LLPRIORITY],[UPPERWARNING],[UPPERACTION],[ULPMNUM],[ULPRIORITY]";

        public const string MEASUREREPLACE = "[MEASURETRANSID],[POINTNUM],[MEASUREUNITID],[MEASUREMENTVALUE],[ENTERBY],[ENTERDATE],[TOPOINTNUM],[TOMEASUREMENTVALUE],[CORRECTEDVALUE],[FROMDEPT],[FROMLOC],[REPLACEPERSON],[REPLACEDATE],[REPLACETYPE],[MEMO],[STATUS],[ORGID],[SITEID]";

        public const string MEASUREMENT = "[MEASUREMENTID],[POINTNUM],[METERNAME],[ORGID],[SITEID],[LOCATION],[BASEMEASUREUNITID],[INSPECTOR],[MEASURETIME],[MEASUREMENTVALUE]";

        public const string MEASUREUNIT = "[MEASUREUNITUID],[CONTENTUID],[MEASUREUNITID],[DESCRIPTION],[ABBREVIATION],[DISPLAYSEQUENCE],[ISCALCULATE],[VISABLED],[ISMAINPARAM],[TYPE],[ORGID],[SITEID]";

        public const string USERS = "[USERID],[USERNAME],[PASSWORD],[ENABLED],[CREATEDDATE],[MODIFIEDDATE],[PASSWORDENCRYPTED],[PASSWORDMODIFIEDDATE],[REALNAME],[DISPLAYNAME],[DIGEST],[EMAILADDRESS],[REMINDERQUERYQUESTION],[REMINDERQUERYANSWER],[TIMEZONE],[LANGUAGE],[GREETING],[WEBSITE],[JOBTITLE],[COMMENTS],[SIGNIFICANTOTHER],[BIRTHDAY],[ANNIVERSARY],[LOGINDATE],[LOGINIP],[LASTLOGINDATE],[LASTLOGINIP],[ISSUPERUSER],[ORGID],[SEX],[WORKPHONE],[WORKMOBILE],[PHONE],[MOBILE],[ADDRESS],[STATUS]";

        public const string GROUPS = "[GROUP_ID],[GROUP_NAME],[DESCRIPTION]";

        public const string GROUP_MEMBERS = "[ID],[USERID],[GROUP_ID]";

    }
}
